# Generated by Django 5.2.11 on 2026-02-17 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('cover_art', models.ImageField(upload_to='covers/')),
                ('spotify_link', models.URLField(blank=True)),
                ('apple_music_link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TourDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('venue', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('ticket_link', models.URLField(blank=True)),
                ('is_sold_out', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('audio_file', models.FileField(blank=True, upload_to='tracks/')),
                ('is_featured', models.BooleanField(default=False)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='web.album')),
            ],
        ),
    ]
