# Generated by Django 5.2.11 on 2026-02-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Product title or name', max_length=200)),
                ('image', models.ImageField(help_text='Transparent PNG image recommended', upload_to='shop/')),
                ('shop_link', models.URLField(help_text='Link to product page')),
                ('is_active', models.BooleanField(default=True, help_text='Show this item in the merch section')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which items are displayed (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shop Item',
                'verbose_name_plural': 'Shop Items',
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
