# Generated by Django 5.2.11 on 2026-02-18 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_shopitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='image',
            field=models.ImageField(help_text='Thumbnail image (transparent PNG recommended)', upload_to='shop/'),
        ),
        migrations.CreateModel(
            name='ShopItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Design variation image (up to 4 images per item)', upload_to='shop/designs/')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which images are displayed')),
                ('shop_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='web.shopitem')),
            ],
            options={
                'verbose_name': 'Shop Item Image',
                'verbose_name_plural': 'Shop Item Images',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
