# Generated by Django 5.2.11 on 2026-02-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_shopitem_image_shopitemimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='youtube_link',
            field=models.URLField(blank=True, help_text='YouTube link for the release'),
        ),
    ]
