# Generated by Django 5.2.11 on 2026-02-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_album_youtube_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='youtube_link',
            field=models.URLField(blank=True, help_text='YouTube link for this track'),
        ),
    ]
