# Generated by Django 5.2.11 on 2026-02-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_track_youtube_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='Upload logo image for MBOKADOBA (replaces text)', upload_to='footer/')),
                ('instagram_link', models.URLField(blank=True, help_text='Instagram profile URL')),
                ('twitter_link', models.URLField(blank=True, help_text='X (Twitter) profile URL')),
                ('facebook_link', models.URLField(blank=True, help_text='Facebook profile URL')),
                ('youtube_link', models.URLField(blank=True, help_text='YouTube channel URL')),
                ('spotify_link', models.URLField(blank=True, help_text='Spotify profile URL')),
                ('music_link', models.URLField(blank=True, help_text='Music platform link (e.g., Apple Music, SoundCloud)')),
                ('copyright_text', models.CharField(default='MBOKADOBA', help_text='Copyright holder name', max_length=200)),
                ('mass_appeal_text', models.CharField(default='mass appeal', help_text='Mass appeal label text', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Footer Settings',
                'verbose_name_plural': 'Footer Settings',
            },
        ),
    ]
