# Generated by Django 5.2.11 on 2026-02-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Optional image for footer upper section (e.g. album cover)', upload_to='footer/'),
        ),
        migrations.AddField(
            model_name='footer',
            name='lets_connect_text',
            field=models.CharField(blank=True, default="LET'S CONNECT", help_text='Heading above social / video area', max_length=100),
        ),
        migrations.AddField(
            model_name='footer',
            name='youtube_video_url',
            field=models.URLField(blank=True, help_text='YouTube video URL to embed in footer (e.g. https://www.youtube.com/watch?v=VIDEO_ID)'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='youtube_link',
            field=models.URLField(blank=True, help_text='YouTube channel URL (for social icon)'),
        ),
    ]
