# Generated by Django 5.2.11 on 2026-02-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_footer_youtube_and_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Order in which items are displayed (lower numbers first)'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Show this item in the merch section'),
        ),
        migrations.AlterField(
            model_name='tourdate',
            name='date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='tourdate',
            name='is_sold_out',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='tourdate',
            index=models.Index(fields=['date', 'is_sold_out'], name='web_tourdat_date_f19cc9_idx'),
        ),
    ]
