# Generated by Django 5.2.11 on 2026-02-20 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_add_query_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Internal name for this ad', max_length=200)),
                ('image', models.ImageField(blank=True, help_text='Image creative for the ad (optional if YouTube Link is provided)', null=True, upload_to='ads/')),
                ('url', models.URLField(blank=True, help_text='Destination URL when a user clicks the standard image ad')),
                ('youtube_link', models.URLField(blank=True, help_text='YouTube link for video ad (Prioritized over image)')),
                ('facebook_link', models.URLField(blank=True, help_text='Facebook URL (If provided, the image acts as a cover routing to Facebook)')),
                ('is_active', models.BooleanField(default=False, help_text='Only the first active ad will be displayed on the frontend')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
