# Generated by Django 5.2.11 on 2026-02-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='featured_image_height',
            field=models.PositiveIntegerField(default=400, help_text='Height of the featured image in pixels (e.g. 300, 400, 500). Width scales automatically.'),
        ),
    ]
