# Generated by Django 5.2.11 on 2026-02-20 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_footer_featured_image_height'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the social network (e.g. Email, Facebook, Spotify)', max_length=50)),
                ('url', models.URLField(help_text='URL for the link (can be a mailto: link for emails)')),
                ('icon', models.FileField(help_text='Upload an SVG or transparent PNG logo', upload_to='footer/socials/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which they appear (lower number first)')),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='web.footer')),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'ordering': ['order'],
            },
        ),
    ]
