# Generated by Django 5.2.11 on 2026-02-20 14:40

from django.db import migrations

def migrate_social_fields(apps, schema_editor):
    Footer = apps.get_model('web', 'Footer')
    SocialLink = apps.get_model('web', 'SocialLink')

    try:
        footer = Footer.objects.get(pk=1)
    except Footer.DoesNotExist:
        return  # No footer yet, nothing to migrate

    # List of tuples: (field_name, social_name)
    socials = [
        ('instagram_link', 'Instagram'),
        ('facebook_link', 'Facebook'),
        ('youtube_link', 'YouTube'),
        ('spotify_link', 'Spotify'),
        ('twitter_link', 'X (Twitter)'),
        ('music_link', 'Music'),
    ]

    order = 0
    # Migrate any existing links
    for field_name, name in socials:
        url = getattr(footer, field_name, '')
        if url:
            SocialLink.objects.create(
                footer=footer,
                name=name,
                url=url,
                order=order
            )
            order += 1
            
    # Add the requested Email link
    SocialLink.objects.create(
        footer=footer,
        name='Email',
        url='mailto:bookings@toxiclyrikali.com',
        order=order
    )

class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_sociallink'),
    ]

    operations = [
        migrations.RunPython(migrate_social_fields),
    ]
