# Generated by Django 5.2.11 on 2026-02-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_migrate_social_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(blank=True, help_text='Background image or GIF for the tour page. If not set, defaults to static image.', upload_to='tour/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tour Settings',
                'verbose_name_plural': 'Tour Settings',
            },
        ),
    ]
