# Generated by Django 5.2.11 on 2026-02-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_toursettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourdate',
            name='map_link',
            field=models.URLField(blank=True, help_text='Google Maps (or other) URL for directions to the venue. Paste the full link (e.g. https://maps.google.com/... or https://goo.gl/maps/...).'),
        ),
    ]
