# Generated by Django 5.2.11 on 2026-02-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_add_tourdate_map_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourdate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
