# Generated by Django 5.2.11 on 2026-02-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_tourdate_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
