# Generated by Django 5.2.11 on 2026-02-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_album_track_updated_at'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='album',
            constraint=models.UniqueConstraint(fields=('title', 'release_date'), name='unique_album_title_release'),
        ),
    ]
