# Generated by Django 5.2.11 on 2026-02-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_album_unique_album_title_release'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sociallink',
            constraint=models.UniqueConstraint(fields=('name', 'url'), name='unique_social_link_name_url'),
        ),
    ]
