# Generated by Django 5.2.11 on 2026-02-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_sociallink_unique_social_link_name_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitemimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
